### ISSUE TITLE
Topmost feature not being returned

### ISSUE THREAD

**Issue by MateoV** [mapbox/vector-tile-query#69]
Surface-api does not seem to be returning the topmost feature anymore. For example when querying contour elevation in `mapbox.vector-terrain-v2` it is returning either the bottommost or possibly a random one. I believe this was resolved at some point but has recently reverted (correct me if I'm wrong @dnomadb ).

This renders surface-api useless in many cases, especially elevation.

Example:
http://api.tiles.mapbox.com/v4/surface/mapbox.mapbox-terrain-v2.json?layer=contour&fields=ele,index&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6IlhHVkZmaW8ifQ.hAMX5hSW-QnTeRCMAy9A8Q&points=-43.15575197339058,-22.949513051950472

returns `"ele":-10,"index":-1`, which are the values of the bottom contour in the tile, although the point that is being queried falls inside a contour that has a value of 300. [see map](https://a.tiles.mapbox.com/v4/matt.lkae5m4a/page.html?access_token=pk.eyJ1IjoibWF0dCIsImEiOiJTUHZkajU0In0.oB-OGTMFtpkga8vC48HjIg#17/-22.94942/-43.15454)

- [link to tile](https://api.tiles.mapbox.com/v4/mapbox.outdoors/14/6227/9265.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6IlhHVkZmaW8ifQ.hAMX5hSW-QnTeRCMAy9A8Q&update=i7zf2)

Example 2 (top of Mt Everest):
http://api.tiles.mapbox.com/v4/surface/mapbox.mapbox-terrain-v2.json?layer=contour&fields=ele,index&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6IlhHVkZmaW8ifQ.hAMX5hSW-QnTeRCMAy9A8Q&points=86.9253945350647,27.988916119554304

[point is at 8740](https://a.tiles.mapbox.com/v4/matt.lkae5m4a/page.html?access_token=pk.eyJ1IjoibWF0dCIsImEiOiJTUHZkajU0In0.oB-OGTMFtpkga8vC48HjIg#16/27.9894/86.9276) but returns 6500

**Comment by dnomadb** [comment]
@MateoV thanks for the heads up. `mapbox.mapbox-terrain-v2` is an untested vector tile source, I will test out the above tiles with `vector-tile-query`.

**Comment by dnomadb** [comment]
Added tests for the two above queries, and they are behaving normally (ie returning the correct values). Going to close this and explore on other fronts.
 - Brazil test: https://github.com/mapbox/vector-tile-query/blob/vector-terrain-v2-tests/test/test.js#L147-L156
 - Everest test: https://github.com/mapbox/vector-tile-query/blob/vector-terrain-v2-tests/test/test.js#L158-L168
 - PR: https://github.com/mapbox/vector-tile-query/pull/70

**Comment by dnomadb** [comment]
Issue appears to actually be connected to sorting order when features are returned from mapnik.queryMany on OSX vs Linux. Fix in process.

**Comment by dnomadb** [comment]
This was fixed in https://github.com/mapbox/vector-tile-query/commit/21aad140f72139f7b0141a5bc8dec7db92c98132
